/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MarketplaceFeeManagerInterface extends Interface {
    getFunction(nameOrSignature: "MAX_FEE_BPS" | "calculateFeeBreakdown" | "calculateMarketFee" | "emergencyWithdraw" | "feeRecipient" | "getFeeInfo" | "marketFeeBps" | "minimumFee" | "owner" | "pause" | "paused" | "renounceOwnership" | "transferOwnership" | "unpause" | "updateFeeRecipient" | "updateMarketFee" | "updateMinimumFee" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FeeRecipientUpdated" | "FeeUpdated" | "FeesWithdrawn" | "MinimumFeeUpdated" | "OwnershipTransferred" | "Paused" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateFeeBreakdown', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateMarketFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFeeInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'marketFeeBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'minimumFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMarketFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateMinimumFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateFeeBreakdown', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateMarketFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFeeInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketFeeBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMarketFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMinimumFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace FeeRecipientUpdatedEvent {
      export type InputTuple = [oldRecipient: AddressLike, newRecipient: AddressLike];
      export type OutputTuple = [oldRecipient: string, newRecipient: string];
      export interface OutputObject {oldRecipient: string, newRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeUpdatedEvent {
      export type InputTuple = [oldFeeBps: BigNumberish, newFeeBps: BigNumberish];
      export type OutputTuple = [oldFeeBps: bigint, newFeeBps: bigint];
      export interface OutputObject {oldFeeBps: bigint, newFeeBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint];
      export interface OutputObject {recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinimumFeeUpdatedEvent {
      export type InputTuple = [oldMinimumFee: BigNumberish, newMinimumFee: BigNumberish];
      export type OutputTuple = [oldMinimumFee: bigint, newMinimumFee: bigint];
      export interface OutputObject {oldMinimumFee: bigint, newMinimumFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MarketplaceFeeManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): MarketplaceFeeManager;
    waitForDeployment(): Promise<this>;

    interface: MarketplaceFeeManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    calculateFeeBreakdown: TypedContractMethod<
      [salePrice: BigNumberish, ],
      [[bigint, bigint] & {marketFee: bigint, sellerAmount: bigint }],
      'view'
    >
    

    
    calculateMarketFee: TypedContractMethod<
      [salePrice: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getFeeInfo: TypedContractMethod<
      [],
      [[bigint, string, bigint] & {feeBps: bigint, recipient: string, minFee: bigint }],
      'view'
    >
    

    
    marketFeeBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minimumFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateFeeRecipient: TypedContractMethod<
      [newFeeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMarketFee: TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateMinimumFee: TypedContractMethod<
      [newMinimumFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateFeeBreakdown'): TypedContractMethod<
      [salePrice: BigNumberish, ],
      [[bigint, bigint] & {marketFee: bigint, sellerAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'calculateMarketFee'): TypedContractMethod<
      [salePrice: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getFeeInfo'): TypedContractMethod<
      [],
      [[bigint, string, bigint] & {feeBps: bigint, recipient: string, minFee: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'marketFeeBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minimumFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFeeRecipient'): TypedContractMethod<
      [newFeeRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMarketFee'): TypedContractMethod<
      [newFeeBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMinimumFee'): TypedContractMethod<
      [newMinimumFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'FeeRecipientUpdated'): TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
getEvent(key: 'FeeUpdated'): TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'MinimumFeeUpdated'): TypedContractEvent<MinimumFeeUpdatedEvent.InputTuple, MinimumFeeUpdatedEvent.OutputTuple, MinimumFeeUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'FeeRecipientUpdated(address,address)': TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
      FeeRecipientUpdated: TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
    

      'FeeUpdated(uint256,uint256)': TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
      FeeUpdated: TypedContractEvent<FeeUpdatedEvent.InputTuple, FeeUpdatedEvent.OutputTuple, FeeUpdatedEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'MinimumFeeUpdated(uint256,uint256)': TypedContractEvent<MinimumFeeUpdatedEvent.InputTuple, MinimumFeeUpdatedEvent.OutputTuple, MinimumFeeUpdatedEvent.OutputObject>;
      MinimumFeeUpdated: TypedContractEvent<MinimumFeeUpdatedEvent.InputTuple, MinimumFeeUpdatedEvent.OutputTuple, MinimumFeeUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }