/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NFTCollectionFactory {
      
    export type CollectionParamsStruct = {name: string, symbol: string, baseURI: string, maxSupply: BigNumberish, description: string}

    export type CollectionParamsStructOutput = [name: string, symbol: string, baseURI: string, maxSupply: bigint, description: string] & {name: string, symbol: string, baseURI: string, maxSupply: bigint, description: string }
  
    }

  export interface NFTCollectionFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allCollections" | "createCollection" | "createCollectionForCreator" | "creatorCollections" | "deploymentFee" | "emergencyWithdraw" | "feeRecipient" | "getAllCollections" | "getCollectionInfo" | "getCreatorCollectionCount" | "getCreatorCollections" | "getTotalCollections" | "isValidCollection" | "maxCollectionsPerCreator" | "owner" | "pause" | "paused" | "renounceOwnership" | "transferOwnership" | "unpause" | "updateDeploymentFee" | "updateFeeRecipient" | "updateMaxCollectionsPerCreator" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CollectionCreated" | "DeploymentFeeUpdated" | "FeeRecipientUpdated" | "MaxCollectionsPerCreatorUpdated" | "OwnershipTransferred" | "Paused" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'allCollections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createCollection', values: [NFTCollectionFactory.CollectionParamsStruct]): string;
encodeFunctionData(functionFragment: 'createCollectionForCreator', values: [NFTCollectionFactory.CollectionParamsStruct, AddressLike]): string;
encodeFunctionData(functionFragment: 'creatorCollections', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deploymentFee', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAllCollections', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCollectionInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCreatorCollectionCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCreatorCollections', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTotalCollections', values?: undefined): string;
encodeFunctionData(functionFragment: 'isValidCollection', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'maxCollectionsPerCreator', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateDeploymentFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateMaxCollectionsPerCreator', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'allCollections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCollection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCollectionForCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creatorCollections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deploymentFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllCollections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollectionInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorCollectionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorCollections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalCollections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isValidCollection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxCollectionsPerCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateDeploymentFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMaxCollectionsPerCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace CollectionCreatedEvent {
      export type InputTuple = [collection: AddressLike, creator: AddressLike, name: string, symbol: string, maxSupply: BigNumberish];
      export type OutputTuple = [collection: string, creator: string, name: string, symbol: string, maxSupply: bigint];
      export interface OutputObject {collection: string, creator: string, name: string, symbol: string, maxSupply: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DeploymentFeeUpdatedEvent {
      export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
      export type OutputTuple = [oldFee: bigint, newFee: bigint];
      export interface OutputObject {oldFee: bigint, newFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeRecipientUpdatedEvent {
      export type InputTuple = [oldRecipient: AddressLike, newRecipient: AddressLike];
      export type OutputTuple = [oldRecipient: string, newRecipient: string];
      export interface OutputObject {oldRecipient: string, newRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MaxCollectionsPerCreatorUpdatedEvent {
      export type InputTuple = [oldMax: BigNumberish, newMax: BigNumberish];
      export type OutputTuple = [oldMax: bigint, newMax: bigint];
      export interface OutputObject {oldMax: bigint, newMax: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NFTCollectionFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): NFTCollectionFactory;
    waitForDeployment(): Promise<this>;

    interface: NFTCollectionFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allCollections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    createCollection: TypedContractMethod<
      [params: NFTCollectionFactory.CollectionParamsStruct, ],
      [string],
      'payable'
    >
    

    
    createCollectionForCreator: TypedContractMethod<
      [params: NFTCollectionFactory.CollectionParamsStruct, creator: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    creatorCollections: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    deploymentFee: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAllCollections: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {collections: string[], total: bigint }],
      'view'
    >
    

    
    getCollectionInfo: TypedContractMethod<
      [collection: AddressLike, ],
      [[boolean, string, bigint] & {isValid: boolean, creator: string, totalSupply: bigint }],
      'view'
    >
    

    
    getCreatorCollectionCount: TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getCreatorCollections: TypedContractMethod<
      [creator: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getTotalCollections: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isValidCollection: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    maxCollectionsPerCreator: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateDeploymentFee: TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateMaxCollectionsPerCreator: TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allCollections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createCollection'): TypedContractMethod<
      [params: NFTCollectionFactory.CollectionParamsStruct, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'createCollectionForCreator'): TypedContractMethod<
      [params: NFTCollectionFactory.CollectionParamsStruct, creator: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'creatorCollections'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'deploymentFee'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllCollections'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {collections: string[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCollectionInfo'): TypedContractMethod<
      [collection: AddressLike, ],
      [[boolean, string, bigint] & {isValid: boolean, creator: string, totalSupply: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorCollectionCount'): TypedContractMethod<
      [creator: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorCollections'): TypedContractMethod<
      [creator: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalCollections'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isValidCollection'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'maxCollectionsPerCreator'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateDeploymentFee'): TypedContractMethod<
      [newFee: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMaxCollectionsPerCreator'): TypedContractMethod<
      [newMax: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CollectionCreated'): TypedContractEvent<CollectionCreatedEvent.InputTuple, CollectionCreatedEvent.OutputTuple, CollectionCreatedEvent.OutputObject>;
getEvent(key: 'DeploymentFeeUpdated'): TypedContractEvent<DeploymentFeeUpdatedEvent.InputTuple, DeploymentFeeUpdatedEvent.OutputTuple, DeploymentFeeUpdatedEvent.OutputObject>;
getEvent(key: 'FeeRecipientUpdated'): TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
getEvent(key: 'MaxCollectionsPerCreatorUpdated'): TypedContractEvent<MaxCollectionsPerCreatorUpdatedEvent.InputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'CollectionCreated(address,address,string,string,uint256)': TypedContractEvent<CollectionCreatedEvent.InputTuple, CollectionCreatedEvent.OutputTuple, CollectionCreatedEvent.OutputObject>;
      CollectionCreated: TypedContractEvent<CollectionCreatedEvent.InputTuple, CollectionCreatedEvent.OutputTuple, CollectionCreatedEvent.OutputObject>;
    

      'DeploymentFeeUpdated(uint256,uint256)': TypedContractEvent<DeploymentFeeUpdatedEvent.InputTuple, DeploymentFeeUpdatedEvent.OutputTuple, DeploymentFeeUpdatedEvent.OutputObject>;
      DeploymentFeeUpdated: TypedContractEvent<DeploymentFeeUpdatedEvent.InputTuple, DeploymentFeeUpdatedEvent.OutputTuple, DeploymentFeeUpdatedEvent.OutputObject>;
    

      'FeeRecipientUpdated(address,address)': TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
      FeeRecipientUpdated: TypedContractEvent<FeeRecipientUpdatedEvent.InputTuple, FeeRecipientUpdatedEvent.OutputTuple, FeeRecipientUpdatedEvent.OutputObject>;
    

      'MaxCollectionsPerCreatorUpdated(uint256,uint256)': TypedContractEvent<MaxCollectionsPerCreatorUpdatedEvent.InputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputObject>;
      MaxCollectionsPerCreatorUpdated: TypedContractEvent<MaxCollectionsPerCreatorUpdatedEvent.InputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputTuple, MaxCollectionsPerCreatorUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }