/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace Marketplace {
      
    export type ListingStruct = {seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, createdAt: BigNumberish, isActive: boolean}

    export type ListingStructOutput = [seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, createdAt: bigint, isActive: boolean] & {seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, createdAt: bigint, isActive: boolean }
  
    }

  export interface MarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "activeListings" | "buyItem" | "cancelListing" | "emergencyCancelListing" | "feeManager" | "getActiveListings" | "getListing" | "getSellerListings" | "isActiveListing" | "listItem" | "listingToIndex" | "listings" | "minimumListingPrice" | "nftToListing" | "owner" | "pause" | "paused" | "renounceOwnership" | "sellerListings" | "supportedTokens" | "transferOwnership" | "unpause" | "updateListingPrice" | "updateMinimumListingPrice" | "updatePaymentToken" | "version"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ItemListed" | "ItemSold" | "ListingCancelled" | "MinimumListingPriceUpdated" | "OwnershipTransferred" | "Paused" | "PaymentTokenUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'activeListings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buyItem', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancelListing', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'emergencyCancelListing', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'feeManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'getActiveListings', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getListing', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSellerListings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isActiveListing', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'listItem', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'listingToIndex', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'listings', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'minimumListingPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'nftToListing', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'sellerListings', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportedTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateListingPrice', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateMinimumListingPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePaymentToken', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'activeListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyCancelListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getActiveListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSellerListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActiveListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listItem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingToIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumListingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nftToListing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sellerListings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateListingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateMinimumListingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePaymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  
    export namespace ItemListedEvent {
      export type InputTuple = [listingId: BytesLike, seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike];
      export type OutputTuple = [listingId: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string];
      export interface OutputObject {listingId: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ItemSoldEvent {
      export type InputTuple = [listingId: BytesLike, buyer: AddressLike, seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, marketFee: BigNumberish, royaltyFee: BigNumberish];
      export type OutputTuple = [listingId: string, buyer: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, marketFee: bigint, royaltyFee: bigint];
      export interface OutputObject {listingId: string, buyer: string, seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, marketFee: bigint, royaltyFee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ListingCancelledEvent {
      export type InputTuple = [listingId: BytesLike, seller: AddressLike, nftContract: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [listingId: string, seller: string, nftContract: string, tokenId: bigint];
      export interface OutputObject {listingId: string, seller: string, nftContract: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MinimumListingPriceUpdatedEvent {
      export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
      export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
      export interface OutputObject {oldPrice: bigint, newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentTokenUpdatedEvent {
      export type InputTuple = [token: AddressLike, supported: boolean];
      export type OutputTuple = [token: string, supported: boolean];
      export interface OutputObject {token: string, supported: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Marketplace extends BaseContract {
    
    connect(runner?: ContractRunner | null): Marketplace;
    waitForDeployment(): Promise<this>;

    interface: MarketplaceInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeListings: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    buyItem: TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'payable'
    >
    

    
    cancelListing: TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyCancelListing: TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    feeManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getActiveListings: TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {listingIds: string[], total: bigint }],
      'view'
    >
    

    
    getListing: TypedContractMethod<
      [listingId: BytesLike, ],
      [Marketplace.ListingStructOutput],
      'view'
    >
    

    
    getSellerListings: TypedContractMethod<
      [seller: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    isActiveListing: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    listItem: TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    listingToIndex: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    listings: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, bigint, boolean] & {seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, createdAt: bigint, isActive: boolean }],
      'view'
    >
    

    
    minimumListingPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nftToListing: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    sellerListings: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    supportedTokens: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateListingPrice: TypedContractMethod<
      [listingId: BytesLike, newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateMinimumListingPrice: TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePaymentToken: TypedContractMethod<
      [token: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeListings'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyItem'): TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelListing'): TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyCancelListing'): TypedContractMethod<
      [listingId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getActiveListings'): TypedContractMethod<
      [offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {listingIds: string[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getListing'): TypedContractMethod<
      [listingId: BytesLike, ],
      [Marketplace.ListingStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSellerListings'): TypedContractMethod<
      [seller: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isActiveListing'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'listItem'): TypedContractMethod<
      [nftContract: AddressLike, tokenId: BigNumberish, price: BigNumberish, paymentToken: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'listingToIndex'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'listings'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, bigint, bigint, string, bigint, boolean] & {seller: string, nftContract: string, tokenId: bigint, price: bigint, paymentToken: string, createdAt: bigint, isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'minimumListingPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nftToListing'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sellerListings'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'supportedTokens'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateListingPrice'): TypedContractMethod<
      [listingId: BytesLike, newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateMinimumListingPrice'): TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePaymentToken'): TypedContractMethod<
      [token: AddressLike, supported: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ItemListed'): TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
getEvent(key: 'ItemSold'): TypedContractEvent<ItemSoldEvent.InputTuple, ItemSoldEvent.OutputTuple, ItemSoldEvent.OutputObject>;
getEvent(key: 'ListingCancelled'): TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
getEvent(key: 'MinimumListingPriceUpdated'): TypedContractEvent<MinimumListingPriceUpdatedEvent.InputTuple, MinimumListingPriceUpdatedEvent.OutputTuple, MinimumListingPriceUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PaymentTokenUpdated'): TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ItemListed(bytes32,address,address,uint256,uint256,address)': TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
      ItemListed: TypedContractEvent<ItemListedEvent.InputTuple, ItemListedEvent.OutputTuple, ItemListedEvent.OutputObject>;
    

      'ItemSold(bytes32,address,address,address,uint256,uint256,address,uint256,uint256)': TypedContractEvent<ItemSoldEvent.InputTuple, ItemSoldEvent.OutputTuple, ItemSoldEvent.OutputObject>;
      ItemSold: TypedContractEvent<ItemSoldEvent.InputTuple, ItemSoldEvent.OutputTuple, ItemSoldEvent.OutputObject>;
    

      'ListingCancelled(bytes32,address,address,uint256)': TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
      ListingCancelled: TypedContractEvent<ListingCancelledEvent.InputTuple, ListingCancelledEvent.OutputTuple, ListingCancelledEvent.OutputObject>;
    

      'MinimumListingPriceUpdated(uint256,uint256)': TypedContractEvent<MinimumListingPriceUpdatedEvent.InputTuple, MinimumListingPriceUpdatedEvent.OutputTuple, MinimumListingPriceUpdatedEvent.OutputObject>;
      MinimumListingPriceUpdated: TypedContractEvent<MinimumListingPriceUpdatedEvent.InputTuple, MinimumListingPriceUpdatedEvent.OutputTuple, MinimumListingPriceUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PaymentTokenUpdated(address,bool)': TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
      PaymentTokenUpdated: TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }